/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MainClasses.App;
import MainPackage.Directory;
import MainPackage.File;
import javax.swing.JLabel;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Angelo
 */
public class CreateFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreateFrame
     */
    private DefaultMutableTreeNode SelectedNode;
    private JTree FilesTree;
    private final App app = App.getInstance();

    public CreateFrame(JTree FilesTree, DefaultMutableTreeNode SelectedNode) {
        
        initComponents();
        
        this.FilesTree = FilesTree;
        this.SelectedNode = SelectedNode;
        this.setBounds(0, 0, 690, 432);
        this.setResizable(false);

    }

    private void updateSliderLabel() {
        String SliderValue = String.valueOf(this.jSlider1.getValue());
        this.SliderValueLabel.setText(SliderValue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SliderValueLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxCreateSelection = new javax.swing.JComboBox<>();
        Create = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Qué desea crear?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 80, 130, 40);

        jLabel3.setText("Nombre del Archivo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 140, 120, 16);

        SliderValueLabel.setText("1");
        jPanel1.add(SliderValueLabel);
        SliderValueLabel.setBounds(530, 190, 70, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(310, 140, 170, 22);

        jSlider1.setMaximum(20);
        jSlider1.setMinimum(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(1);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel1.add(jSlider1);
        jSlider1.setBounds(300, 190, 200, 28);

        jLabel5.setText("Tamaño en Bloques");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 190, 120, 16);

        ComboBoxCreateSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Archivo", "Directorio" }));
        ComboBoxCreateSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCreateSelectionActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBoxCreateSelection);
        ComboBoxCreateSelection.setBounds(310, 90, 86, 22);

        Create.setText("Crear");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        jPanel1.add(Create);
        Create.setBounds(340, 310, 72, 23);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 310, 75, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        updateSliderLabel();
    }//GEN-LAST:event_jSlider1StateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ComboBoxCreateSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCreateSelectionActionPerformed
        // Atributos dinamicos
        JLabel[] JLabelArray = {jLabel3, jLabel5};

        // Logica para la creacion de un archivo o directorio
        String selectedItem = this.ComboBoxCreateSelection.getModel().getSelectedItem().toString();

        if (selectedItem.equalsIgnoreCase("Archivo")) {
            JLabelArray[0].setText("Nombre del Archivo");

            JLabelArray[1].setVisible(true);
            this.jSlider1.setVisible(true);

        } else {
            JLabelArray[0].setText("Nombre del Directorio");
            JLabelArray[1].setVisible(false);
            this.jSlider1.setVisible(false);
        }

    }//GEN-LAST:event_ComboBoxCreateSelectionActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        /*
        CREACION DEL ARCHIVO
         */

        String ElementToCreate = ComboBoxCreateSelection.getModel().getSelectedItem().toString();
        if (ElementToCreate.equalsIgnoreCase("Archivo")) {
            // Creamos el File
            String FileName = jTextField1.getText();
            int BlockSize = jSlider1.getModel().getValue();

            File NewFile = new File(FileName, BlockSize, null, null, null);

            boolean AccessToSD = app.getFileSystemApp().searchAndSet(NewFile.getBlockSize(), NewFile);

            if (AccessToSD) {
                System.out.println("El valor ha sido colocado en la SD");
                
                // Colocando el nuevo nodo en la estructura jtree
                DefaultMutableTreeNode NewNode = new DefaultMutableTreeNode(NewFile.getFileName());
                
                if (this.SelectedNode != null) {
                    DefaultTreeModel Model = (DefaultTreeModel) this.FilesTree.getModel();
                    Model.insertNodeInto(NewNode, this.SelectedNode, this.SelectedNode.getChildCount());
                }
            }
        } else {
            
            String DirectoryName = jTextField1.getText();
            Directory NewDirectory = new Directory(DirectoryName, null, null);
        }

    }//GEN-LAST:event_CreateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateFrame(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCreateSelection;
    private javax.swing.JButton Create;
    private javax.swing.JLabel SliderValueLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
